services:
  db:
    build: .
    environment:
      - POSTGRES_USER=eva
      - POSTGRES_PASSWORD=31415
      - POSTGRES_DB=lab4_docker
    ports:
      - "5433:5432"
  spring:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db